M48
; DRILL file {KiCad 9.0.6} date 2025-11-15T14:01:42-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-15T14:01:42-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.200
%
G90
G05
T1
X141.96Y-93.5
X144.5Y-93.5
T2
X104.5Y-119.5
X104.5Y-124.0
X111.0Y-119.5
X111.0Y-124.0
T3
X144.5Y-116.49
X144.5Y-124.11
M30
